name: Build documentation

on:
  push:
    tags:
      - v[0-9]+.[0-9]+
  # Specify to run a workflow manually from the Actions tab on GitHub
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

env:
  # Name of module and id separated by a slash
  INSTANCE: mydocs/js
  # Replace XX with the ID of the instance in capital letters
  ARTIFACT: webHelpJS2-all.zip

jobs:
  build:
    strategy:
      matrix:
        version: [v1, v2]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ matrix.version }}

      - name: Build Writerside docs using Docker
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-${{ matrix.version }}
          path: |
            artifacts/${{ env.ARTIFACT }}
            artifacts/report.json
          retention-days: 3

    # Add the job below and artifacts/report.json on Upload documentation step above if you want to fail the build when documentation contains errors
  test:
    needs: build
    strategy:
      matrix:
        version: [v1, v2]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs-${{ matrix.version }}
          path: artifacts

      - name: Test documentation
        uses: JetBrains/writerside-checker-action@v1
        with:
          instance: ${{ env.INSTANCE }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}${{ vars.STABLE_VERSION }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download docs
        uses: actions/download-artifact@v4

      - name: Generate documents destination
        run: |
          mkdir -p dist/v1 && mkdir dist/${{ vars.STABLE_VERSION }}

      - name: Unzip docs
        run: |
          unzip -qq docs-v1/${{ env.ARTIFACT }} -d dist/v1
          unzip -qq docs-${{ vars.STABLE_VERSION }}/${{ env.ARTIFACT }} -d dist/${{ vars.STABLE_VERSION }}

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
